### ISSUE TITLE
Some Japanese city names don't work as nearby city when entered in English

### ISSUE THREAD

**Issue by naokomc** [coreymckrill/nearby-wordpress-events#37]
Currently, there are only two events scheduled in Japan (WordCamp Kyoto & Tokyo) - this ok, since we are not using meetup.com as event platform for localization reasons.

If I enter one of these, the widget finds both of the WordCamps: Tokyo, Kyoto, Osaka, 東京 ("Tokyo" in Japanese), 京都 ("Kyoto"), 横浜 ("Yokohama")

But If I enter 大阪 ("Osaka"  - which worked fine as an English city name), it returns "We couldn't locate XX. Please try typing..." error.

I think it's neat Japanese city names work at all, but it's even better if it always works just the same as English names.

**Comment by iandunn** [comment]
> If I enter 大阪  it returns "We couldn't locate XX. Please try typing..." error.

I see what went wrong. The database only has `大阪市`, not `大阪`. I'm guessing that `市` is the name of the region, right?

The API uses a MySQL full-text search for most languages, which would match cases where the region is included in the name. For ideographic languages, though, [it uses a `LIKE` query](https://meta.trac.wordpress.org/browser/sites/trunk/api.wordpress.org/public_html/events/1.0/index.php?rev=5355#L268), because [MySQL doesn't support fulltext searches for ideographic languages very well](https://dev.mysql.com/doc/refman/5.7/en/fulltext-restrictions.html) (because it doesn't know where the word boundaries are).

Right now, the query only looks for exact matches, because otherwise it would result in too many false positives.

So, I'm not sure that we have a lot of options to fix that, unless we add a lot of complex code, or just throw out our API and start using a real geocoding service. We probably should do that long term, but that's probably too big of a project for v1. 

Maybe we can improve the instructions for ideographic languages, and ask users to re-try the search with the region name included? I don't want to make the instructions too lengthy or complicated, though.

What do you think?

>we are not using meetup.com as event platform for localization reasons.

I'd love to get your meetups listed. Mayo and I [discussed it a bit on make/Community](https://make.wordpress.org/community/2017/03/23/showing-upcoming-local-events-in-wp-admin/#comment-23204).

Let me know if you have any ideas or if any local developers want to contribute a patch. I'd be happy to work with them.

**Comment by naokomc** [comment]
Thanks for the explanation, makes sense.

Yes, `市` is a municipal unit in Japan, similar to a city or borough. I tried "Osaka-shi" and "大阪市" again and they both worked (both WordCamps showed up as nearby events, and Osaka was displayed as a currently selected city). "Osakashi" didn't work.

> improve the instructions for ideographic languages, and ask users to re-try the search with the region name included? 

That sounds like a good workaround for now.

How about changing this:

> We couldn't locate <strong><em>%s</em></strong>. Please try typing only the city name, or try another nearby city, or your closest airport code.

to this?

> We couldn't locate <strong><em>%s</em></strong>. Please try typing only the city name, city name in latin characters, another nearby city, or your closest airport code.

A bit longer compared to the original, but serves the purpose.
Please feel free to rewrite.

**Comment by iandunn** [comment]
I think I improved things with 5cf35a8. I think in most cases (globally), trying another nearby city will be the fastest and most successful suggestion for the user.

When that fails, then trying variations on the city name is the best choice. Since the edge cases are different for each locale, though, the translator is asked to provide specific examples that work in their locale. 

I think the translator will be able to provide much better instructions to the user than anything generic we could come up with.

How does that look?

**Comment by iandunn** [comment]
Actually, I just thought of a way to solve the 大阪 issue without causing any unintended side-effects:

https://meta.trac.wordpress.org/changeset/5409/

I think that should make similar cases work, too. @naokomc, would you mind testing a few examples, and then re-open this issue if you find anything that doesn't work?

**Comment by iandunn** [comment]
Doh, I just realized I forgot about `Osakashi`. I think I have an idea of how to make that work, so I'll play around with that next week.

**Comment by iandunn** [comment]
@naokomc, I fixed the problem with `osakashi` in https://meta.trac.wordpress.org/changeset/5417/

I'm not sure if it'll work for all cities with all variations, though, so let me know if you notice any other problems.

**Comment by naokomc** [comment]
Thank you!!
I've tested with some other cities - so far I haven't run into any issues. Looks great.

**Comment by iandunn** [comment]
That's great! I'm glad to hear it :D
