### ISSUE TITLE
Convert admin-AJAX endpoint to REST API

### ISSUE THREAD

**Issue by iandunn** [coreymckrill/nearby-wordpress-events#52]
New features in Core are being implemented with the REST API, and old features are being migrated to it, so it doesn't make sense to add a new feature with admin-AJAX.

**Comment by coreymckrill** [comment]
See this branch: https://github.com/coreymckrill/nearby-wordpress-events/tree/rest-api

**Comment by rmccue** [comment]
👋 @dd32 pinged me for input on this.

Looking at the branch, couple of things pop up for me:

1. Since this is an internal API for the dashboard, not for external use, I'd pick a different namespace. `dashboard/v1` is one namespace we're looking at potentially using for other dashboard-specific items (or potentially `wp/dashboard/v1`).
2. Routes should be dashed (like slugs), not underscored (like functions), so `nearby-events` rather than `nearby_events`
3. The controller feels like it has a bit too much boilerplate right now. REST endpoints can be as simple as `register_rest_route( 'dashboard/v1', '/nearby-events', array( 'callback' => function () {} ) )`, so there's no need for a full controller unless you need one. Since this is only a small piece of functionality, it would be likely be fine to simply use a singular callback here instead.

I'm in the process of writing up better design docs for core endpoints to outline these things better (and get them out of my head and into something permanent). In the meantime, happy to provide more feedback :)

**Comment by iandunn** [comment]
Thanks Ryan, that's really helpful. I'll make those changes today :)

**Comment by iandunn** [comment]
[The rough draft of the merge patch](https://gist.github.com/iandunn/d2569bdfc70f671062db83548d2f4168) has those changes incorporated, but I haven't backported them to this repo to save time.

**Comment by iandunn** [comment]
Hey @rmccue, I created a [ticket](https://core.trac.wordpress.org/ticket/40702) and patch on `core.trac`; do you mind taking a final look at it if you have a chance before the merge deadline?

**Comment by iandunn** [comment]
This is being worked on by the API team in https://core.trac.wordpress.org/ticket/40702.
